# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/DEEKSHITH/Desktop/Study/5th Sem/VHDL/Lab/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/DEEKSHITH/Desktop/Study/5th Sem/VHDL/Lab/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
read_verilog -library xil_defaultlib {{C:/Users/DEEKSHITH/Desktop/Study/5th Sem/VHDL/Lab/project_1/project_1.srcs/sources_1/new/abc.v}}
synth_design -top abc -part xc7a200tfbg676-2
write_checkpoint -noxdef abc.dcp
catch { report_utilization -file abc_utilization_synth.rpt -pb abc_utilization_synth.pb }
